= Cloud Native Architectures Workshop
In this hands-on workshop participants will learn how to leverage OpenShift and Application Services to design, develop and deploy modern cloud-native applications, based on real life use cases.

The workshop uses a pick-your-adventure style. Participants can choose which modules they want to go through, depending on interest. Each module is independent from the others. Participants deploy and undeploy the module assets on demand.

== The different modules cover the following topics:

* Modernization: use Change Data Capture to build new functionality #Debezium #AMQStreams #CamelK #Quarkus
* API Management: use a Contract First API development to create new channels in a secure way #3scale #RHSSO #Apicurio
* Integration: build a multichannel support service integrating several instant messaging solutions. #Camel #AMQStreams #Quarkus #DataGrid #AMQBroker
* Application Connectivity: connect disparate services over cloud and data center boundaries. #ServiceInterconnect
* Serverless Event Driven Architecture: build an event driven application, without having to deal with the underlying messaging infrastructure. #OpenShiftServerless #AMQStreams #Quarkus

== Key Takeaways:

* Learn how to build and deploy modern cloud-native applications.
* Get introduced to various architectural patterns, technologies and tools.
* Learn how you can use this repeatable workshop to gain customer/partner developer mindshare.
