= Launch new channels with Contract First Approach - Intro
:imagesdir: ../assets/images



++++
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-51D1EZEH8B"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-51D1EZEH8B');
</script>
<style>
  .underline {
    cursor: pointer;
  }

  .nav-container {
    display: none !important;
  }

  .doc {    
    max-width: 70rem !important;
  }

  .pagination .prev {
    display: none !important;
  }
</style>

</style>
++++

== What is Contract First Approach?

Contract-first development is a design approach where the API contract is defined before any actual code is written. The stakeholders, including business users and developers first agree upon the Contract using a definition language such as OpenAPI Specification (OAS) or AsyncAPI. This contract serves as a blueprint for the API, the structure, data formats and expected behavior, authentication methods, and other relevant information.

This approach is particularly beneficial in microservices and API-based systems, as it provides a clear contract that can be used to guide development, testing, and integration. It also facilitates collaboration between teams, as the contract serves as a shared understanding of the API's capabilities and requirements.

In this module you'll discover how Contract First Approach provides the right framework to accelerate the launching of new channels in a secure way across internal and external teams to build microservices and APIs based systems.

== Business context

As mentioned in the introduction module of the workshop, Globex went through a modernization phase for their retail web application, moving from a legacy monolith to a containerized application. With their growing popularity, Globex would like to add new channels to their existing, web-based e-commerce application.


They are working towards launching their own *Globex Mobile App* and  partnering with other large retail portals. This requires formalizing the application API definitions and exposing the APIs through an API Management solution for consumption by the Globex Mobile App and by Partner portals.


*(a) Mobile App*

* Globex plans to launch a mobile application alongside their retail website. Since Globex lacks the necessary expertise in mobile development, this work will have to be outsourced.
* Therefore, the mobile application must have secure access to Globex's APIs

*(b) Partner Portal*

* Retail partner aggregators are interested in displaying Globex's product catalog on their websites.
* To enable this, Globex plans to expose the necessary functionality through an API.