= Launch new channels with Contract First Approach - Intro
:imagesdir: ../assets/images



++++
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-51D1EZEH8B"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-51D1EZEH8B');
</script>
<style>
  .underline {
    cursor: pointer;
  }

  .nav-container {
    display: none !important;
  }

  .doc {    
    max-width: 70rem !important;
  }

  .pagination .prev {
    display: none !important;
  }
</style>

</style>
++++

In this module you'll discover how Contract First Approach provides the right framework to accelerate the launching of new channels in a secure way across internal and external teams to build microservices and APIs based systems.

== Business context

As mentioned in the introduction module of the workshop, Globex went through a modernization phase for their retail web application, moving from a legacy monolith to a containerized application. With their growing popularity, Globex would like to add new channels to their existing, web-based e-commerce application.


They are working towards launching their own *Globex Mobile App* and  partnering with other large retail portals. This requires formalizing the application API definitions and exposing the APIs through a API Management solution for consumption by the Globex Mobile App and by partner's portals.


*(a) Mobile App*

* Globex would like to launch a mobile application in addition to the retail web-site. Globex does not have the necessary expertise in mobile development, so development will have to be outsourced.
* This means that the mobile application will also need secure access to the Globex APIs

*(b) Partner Portal*

* Retail partner aggregators would like to showcase Globex's product catalogue on their website
* To allow this access, Globex would like to expose an API


